# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h6Zpt-mzKqMpDuJB2276-I7NIftDf3yq
"""

!pip install streamlit
import streamlit as st
import pandas as pd
import numpy as np
import pickle
from sklearn.impute import SimpleImputer
import warnings
warnings.filterwarnings('ignore')

st.set_page_config(page_title="California House Price Predictor", layout="wide")

st.title("🏠 California House Price Predictor")
st.markdown("AI-powered housing price prediction using Gradient Boosting ML Model")

col1, col2 = st.columns([1, 1])

with col1:
    st.subheader("📍 Location")
    latitude = st.number_input("Latitude", value=37.88, min_value=-90.0, max_value=90.0, step=0.01)
    longitude = st.number_input("Longitude", value=-122.23, min_value=-180.0, max_value=180.0, step=0.01)

    ocean_options = ["<1H OCEAN", "INLAND", "ISLAND", "NEAR BAY", "NEAR OCEAN"]
    ocean_proximity = st.selectbox("Ocean Proximity", options=ocean_options, index=3)

with col2:
    st.subheader("🏠 House Details")
    housing_median_age = st.number_input("House Age (years)", value=41, min_value=0, max_value=100, step=1)
    total_rooms = st.number_input("Total Rooms", value=2600, min_value=0, step=1)
    total_bedrooms = st.number_input("Total Bedrooms", value=440, min_value=0, step=1)
    households = st.number_input("Households", value=400, min_value=0, step=1)

st.subheader("👥 Demographics")
col3, col4 = st.columns([1, 1])

with col3:
    population = st.number_input("Population", value=1200, min_value=0, step=1)

with col4:
    median_income = st.number_input("Median Income ($10,000s)", value=8.3, min_value=0.0, step=0.1)

st.markdown("---")

@st.cache_resource
def load_model_and_imputer():
    try:
        with open('gb_model.pkl', 'rb') as f:
            model = pickle.load(f)
        st.success("✅ Model loaded successfully!")
        return model
    except FileNotFoundError:
        st.error("❌ Model file not found. Please upload gb_model.pkl")
        return None

gb_model = load_model_and_imputer()

def preprocess_input(latitude, longitude, housing_median_age, total_rooms,
                     total_bedrooms, population, households, median_income, ocean_proximity):

    input_data = pd.DataFrame({
        'longitude': [longitude],
        'latitude': [latitude],
        'housing_median_age': [housing_median_age],
        'total_rooms': [total_rooms],
        'total_bedrooms': [total_bedrooms],
        'population': [population],
        'households': [households],
        'median_income': [median_income],
        'ocean_proximity': [ocean_proximity]
    })

    input_processed = pd.get_dummies(input_data, columns=['ocean_proximity'], drop_first=True)

    expected_cols = ['longitude', 'latitude', 'housing_median_age', 'total_rooms',
                     'total_bedrooms', 'population', 'households', 'median_income',
                     'ocean_proximity_INLAND', 'ocean_proximity_ISLAND',
                     'ocean_proximity_NEAR BAY', 'ocean_proximity_NEAR OCEAN']

    for col in expected_cols:
        if col not in input_processed.columns:
            input_processed[col] = 0

    input_processed = input_processed[expected_cols]

    imputer = SimpleImputer(strategy='median')

    input_imputed = pd.DataFrame(imputer.fit_transform(input_processed),
                                  columns=input_processed.columns)

    return input_imputed

if gb_model is not None:
    input_data = preprocess_input(latitude, longitude, housing_median_age, total_rooms,
                                   total_bedrooms, population, households, median_income, ocean_proximity)

    predicted_price = gb_model.predict(input_data)[0]

    st.metric(
        label="💰 Estimated House Price",
        value=f"${predicted_price:,.2f}",
        delta=None
    )

    col5, col6 = st.columns([1, 1])

    with col5:
        st.info(f"""
        **Input Summary:**
        - Latitude: {latitude:.2f}
        - Longitude: {longitude:.2f}
        - Ocean Proximity: {ocean_proximity}
        - House Age: {housing_median_age} years
        - Total Rooms: {total_rooms}
        - Total Bedrooms: {total_bedrooms}
        - Population: {population}
        - Households: {households}
        - Median Income: ${median_income*10000:,.0f}
        """)

    with col6:
        st.success(f"""
        **Model Information:**
        - Algorithm: Gradient Boosting Regressor
        - Features: 9 (including one-hot encoded)
        - Test R² Score: 0.571
        - Test RMSE: $73,481.09
        - Test MAE: $53,321.59
        """)

    st.markdown("---")

    st.subheader("⚡ Quick Examples")

    example_col1, example_col2, example_col3, example_col4 = st.columns(4)

    examples = {
        "Budget": {
            "latitude": 37.40,
            "longitude": -122.10,
            "housing_median_age": 50,
            "total_rooms": 1800,
            "total_bedrooms": 300,
            "population": 3000,
            "households": 250,
            "median_income": 3.5,
            "ocean_proximity": "INLAND"
        },
        "Luxury": {
            "latitude": 37.88,
            "longitude": -122.45,
            "housing_median_age": 20,
            "total_rooms": 4000,
            "total_bedrooms": 800,
            "population": 800,
            "households": 200,
            "median_income": 15.0,
            "ocean_proximity": "NEAR OCEAN"
        },
        "New": {
            "latitude": 37.75,
            "longitude": -122.35,
            "housing_median_age": 5,
            "total_rooms": 3500,
            "total_bedrooms": 700,
            "population": 1000,
            "households": 350,
            "median_income": 10.0,
            "ocean_proximity": "<1H OCEAN"
        },
        "Island": {
            "latitude": 37.50,
            "longitude": -122.20,
            "housing_median_age": 35,
            "total_rooms": 3000,
            "total_bedrooms": 600,
            "population": 500,
            "households": 150,
            "median_income": 12.0,
            "ocean_proximity": "ISLAND"
        }
    }

    if example_col1.button("🏠 Budget Home"):
        st.session_state.example = "Budget"
        st.rerun()

    if example_col2.button("✨ Luxury Home"):
        st.session_state.example = "Luxury"
        st.rerun()

    if example_col3.button("🆕 New House"):
        st.session_state.example = "New"
        st.rerun()

    if example_col4.button("🏝️ Island Property"):
        st.session_state.example = "Island"
        st.rerun()

    if 'example' in st.session_state:
        ex = examples[st.session_state.example]
        st.markdown("---")
        st.subheader(f"Example: {st.session_state.example} Home")
        ex_input = preprocess_input(ex['latitude'], ex['longitude'], ex['housing_median_age'],
                                     ex['total_rooms'], ex['total_bedrooms'], ex['population'],
                                     ex['households'], ex['median_income'], ex['ocean_proximity'])
        ex_price = gb_model.predict(ex_input)[0]

        col_ex1, col_ex2 = st.columns([1, 1])
        with col_ex1:
            st.write(f"**Location:** ({ex['latitude']:.2f}, {ex['longitude']:.2f})")
            st.write(f"**Ocean:** {ex['ocean_proximity']}")
            st.write(f"**Age:** {ex['housing_median_age']} years")
            st.write(f"**Rooms:** {ex['total_rooms']} total")

        with col_ex2:
            st.write(f"**Bedrooms:** {ex['total_bedrooms']}")
            st.write(f"**Population:** {ex['population']}")
            st.write(f"**Income:** ${ex['median_income']*10000:,.0f}")
            st.write(f"**Estimated Price:** ${ex_price:,.2f}")

    st.markdown("---")

    st.markdown("""
    ### 📊 About This Model
    - **Dataset:** California Housing Dataset (1990 Census)
    - **Algorithm:** Gradient Boosting Regressor
    - **Accuracy (R² Score):** 0.571 on test data
    - **Features Used:** 9 (Location, House Details, Demographics)
    - **Training/Test Split:** 80/20

    This model predicts median house values based on various demographic and housing features.
    Actual prices may vary based on market conditions and other factors.

    **Model Performance:**
    - Test RMSE: $73,481.09
    - Test MAE: $53,321.59
    """)

else:
    st.error("⚠️ Model could not be loaded. Please ensure gb_model.pkl is in the same directory as app.py")